### ISSUE TITLE
execute_command

### ISSUE THREAD

**Issue by huwade** [RedisGears/AnimalRecognitionDemo#12]
Hi, I am new for Redis
In init.py, line 37, what does execute_command mean? and how to set the parameters

Thanks

**Comment by MeirShpilraien** [comment]
execute_command means performing a command on the redis server. Regarding parameters, not sure what you mean, what parameters do you want to set?

**Comment by huwade** [comment]
Thanks for you reply, I found this website https://oss.redislabs.com/redisai/commands/ can solve my problem. thanks again.

**Comment by MeirShpilraien** [comment]
@huwade Pls notice that in this demo RedisGears uses the C api exposed by RedisAI to integrate with RedisAI:
From : https://github.com/RedisGears/AnimalRecognitionDemo/blob/master/app/gear.py
```
    # converting the matrix color to Tensor
    v1 = redisAI.createTensorFromBlob('FLOAT', [1, 224, 224, 3], img_ba)

    # creating the graph runner, 'g1' is the key in redis on which the graph is located
    graphRunner = redisAI.createModelRunner('mobilenet:model')
    redisAI.modelRunnerAddInput(graphRunner, 'input', v1)
    redisAI.modelRunnerAddOutput(graphRunner, 'MobilenetV2/Predictions/Reshape_1')
```
So the api is a little different then issuing commands to redis..

**Comment by MeirShpilraien** [comment]
# converting the matrix color to Tensor
    v1 = redisAI.createTensorFromBlob('FLOAT', [1, 224, 224, 3], img_ba)

    # creating the graph runner, 'g1' is the key in redis on which the graph is located
    graphRunner = redisAI.createModelRunner('mobilenet:model')
    redisAI.modelRunnerAddInput(graphRunner, 'input', v1)
    redisAI.modelRunnerAddOutput(graphRunner, 'MobilenetV2/Predictions/Reshape_1')

**Comment by MeirShpilraien** [comment]
@huwade did you found all the answers you were looking for? Can we close this issue?

**Comment by huwade** [comment]
yes, thx.
