### ISSUE TITLE
Question, why py2 and py3?

### ISSUE THREAD

**Issue by robmarkcole** [RedisGears/AnimalRecognitionDemo#7]
Hi chaps
sorry for raising this question as an issue, but I am curious to know why you are mixing python 2.7 and python 3 - is it a requirement flowing from Redis?

https://github.com/RedisGears/AnimalRecognitionDemo/tree/master/camera

**Comment by hrisheekeshr** [comment]
Why would you code this in Python2 given it's going to be obsolete in 3 months? Is there a specific reason or dependency?

**Comment by MeirShpilraien** [comment]
Redisgears early releases supported python2 only. On v0.3.0 RedisGears moved to python 3.7. We still migrating the demos code to python3.
