### ISSUE TITLE
ERROR: Service 'redis' failed to build, on "docker compose up"

### ISSUE THREAD

**Issue by KNCal** [RedisGears/AnimalRecognitionDemo#8]
Building redis
Step 1/12 : FROM redisai/redisai:0.2.0 as redisai
 ---> ce1c6cb778a1
Step 2/12 : FROM redislabs/redisgears:0.2.1 as redisgears
 ---> 07197f1f0c14
Step 3/12 : ENV LD_LIBRARY_PATH /usr/lib/redis/modules/
 ---> Using cache
 ---> 533d0c1c0eb7
Step 4/12 : ENV RUNTIME_DEPS "python python-setuptools python-pip python-dev build-essential libglib2.0-0 libsm6 libxext6 libfontconfig1 libxrender1"
 ---> Using cache
 ---> b62811ab9436
Step 5/12 : ENV PYTHON_DEPS "setuptools redis argparse imageio opencv-python pybase64 redisAI"
 ---> Using cache
 ---> 50ba217e3446
Step 6/12 : WORKDIR /data
 ---> Using cache
 ---> e14218f97277
Step 7/12 : RUN set -ex;    apt-get update;    apt-get install -y --no-install-recommends $RUNTIME_DEPS;
 ---> Using cache
 ---> af0f0d09fe33
Step 8/12 : COPY --from=redisai /usr/lib/redis/modules/*.so* "$LD_LIBRARY_PATH"
 ---> Using cache
 ---> 88fbf8361961
Step 9/12 : RUN pip install -t /usr/local/lib/python2.7/site-packages ${PYTHON_DEPS}
 ---> Running in 483aef515785
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
Collecting redis
  Downloading https://files.pythonhosted.org/packages/bd/64/b1e90af9bf0c7f6ef55e46b81ab527b33b785824d65300bb65636534b530/redis-3.3.8-py2.py3-none-any.whl (66kB)
Collecting argparse
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting imageio
  Downloading https://files.pythonhosted.org/packages/69/4a/0387d708394d5e25d95b1abe427c301614152d1bebea18d9b06fa7199704/imageio-2.5.0.tar.gz (3.3MB)
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/1e/c8/37b2c4520fcb24e68c1b2a9e20dee679ac813bc6750777aa5ba064c8056f/opencv_python-4.1.1.26-cp27-cp27mu-manylinux1_x86_64.whl (28.7MB)
Collecting pybase64
  Downloading https://files.pythonhosted.org/packages/d1/c7/89df3b35659ba043f879ded41a1b9120adca79c026535657fa213bc28ec0/pybase64-0.5.0-cp27-cp27mu-manylinux1_x86_64.whl (62kB)
Collecting redisAI
  Downloading https://files.pythonhosted.org/packages/97/42/a168b8c36c5b4f7f28df5daa2178f66b9a9abbb061e23eb7868393224a1a/redisai-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UEP3Xr/redisAI/setup.py", line 5, in <module>
        exec(open('redisai/version.py', encoding='utf-8').read())
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UEP3Xr/redisAI/
ERROR: Service 'redis' failed to build: The command '/bin/sh -c pip install -t /usr/local/lib/python2.7/site-packages ${PYTHON_DEPS}' returned a non-zero code: 1

**Comment by K-Jo** [comment]
@KNCal should have been fixed in https://github.com/RedisGears/AnimalRecognitionDemo/commit/c8acfd8aabf573c978ce694b6e0e61a4b05b8b06

**Comment by KNCal** [comment]
Yes, it is building successfully now.  Thank you!
